defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
markdown: kramdown
sass:
  compressed: true
  sass_dir: _sass
exclude:
  - .circleci
  - .gitignore
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
